AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  TagEnvironment:
    Type: String
    Default: production
    Description: The environment tag to be used for the resources.
  TagProject:
    Type: String
    Default: studying-serverless
    Description: The project tag to be used for the resources.


